version: "3.1"
services:
  NginxProxyManager:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "exampleuser"
      DB_MYSQL_PASSWORD: "examplepass"
      DB_MYSQL_NAME: "exampledb"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 0
    volumes:
      - wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  nextcloud:
    image: nextcloud:latest
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - wordpress:/var/www/html/data/website/files
    environment:
      MYSQL_HOST: db
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb

  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      MYSQL_ROOT_PASSWORD: "npm"
    volumes:
      - db:/var/lib/mysql
      
      
      
  wordpress-g:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db-g
      WORDPRESS_DB_USER: exampleuser-g
      WORDPRESS_DB_PASSWORD: examplepass-g
      WORDPRESS_DB_NAME: exampledb-g
      WORDPRESS_DEBUG: 0
    volumes:
      - wordpress-g:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      
  db-g:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_USER: exampleuser-g
      MYSQL_PASSWORD: examplepass-g
      MYSQL_DATABASE: exampledb-g
      MYSQL_ROOT_PASSWORD: "npm"
    volumes:
      - db-g:/var/lib/mysql

volumes:
  wordpress:
  db:
  data:
  letsencrypt:
  nextcloud:

networks:
  default:
    external:
      name: proxy
